# Generated by Django 2.2.6 on 2019-10-25 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('user_profile', '0002_settings'), ('user_profile', '0003_auto_20191025_0718'), ('user_profile', '0004_auto_20191025_1040'), ('user_profile', '0005_auto_20191025_1311'), ('user_profile', '0006_auto_20191025_1315'), ('user_profile', '0007_auto_20191025_1417')]

    dependencies = [
        ('user_profile', '0001_squashed_0005_auto_20191022_1727'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='', max_length=255)),
                ('email_host_user', models.CharField(max_length=255)),
                ('email_host_password', models.CharField(max_length=500)),
                ('email_port', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Email post is not valid. Email post format should be 000 in digits.', regex='[0-9]{3}')])),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
            ],
        ),
    ]
