# Generated by Django 2.2.6 on 2019-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='email_post',
            new_name='email_port',
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_host',
            field=models.CharField(default='', max_length=255),
        ),
    ]
