# Generated by Django 2.2.6 on 2019-10-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20191025_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_host_password',
            field=models.CharField(max_length=500),
        ),
    ]
