# Generated by Django 2.2.6 on 2019-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20191025_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_host_password',
            field=models.CharField(max_length=500),
        ),
    ]
