# Generated by Django 2.2.6 on 2019-10-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20191025_1315'),
    ]

    operations = [
        migrations.RenameModel('Settings', 'SitesSettings')
    ]
